LIB := $(CUR_DIR)\lib
MAKE := make
MKDIR := md

.PHONY : all clean

all : libs

libs :
	-$(MKDIR) $(LIB)
	for %%f in ($(SUBDIRS)) do cd %%f && $(MAKE) OUTPUT_DIR=$(LIB)

clean :
	for %%f in ($(SUBDIRS)) do cd %%f && $(MAKE) clean
	rm -rf lib/*
